server:
  port: 8090   

spring:
  application:
    name: admin-server

  security:
    user:
      name: ${ADMIN_SERVER_USERNAME:0191cs221060@technocratsgroup.edu.in}
      password: ${ADMIN_SERVER_PASSWORD:admin123}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
